anguage: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
install:
  - virtualenv env --python=python3
  - source env/bin/activate
  - pip install -r requirements.txt
script:
  - scripts/pre-commit-checks
after_success:
  - codecov
